/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChannelsList: typeof import('./src/components/ChannelsList.vue')['default']
    ColorPickerComponent: typeof import('./src/components/ColorPickerComponent.vue')['default']
    EditMessagePopup: typeof import('./src/components/EditMessagePopup.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    MembersList: typeof import('./src/components/MembersList.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MessagePageView: typeof import('./src/components/pages/MessagePageView.vue')['default']
    NewChannelPopup: typeof import('./src/components/NewChannelPopup.vue')['default']
    NewPopup: typeof import('./src/components/NewPopup.vue')['default']
    NotFoundView: typeof import('./src/components/pages/NotFoundView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorPicker: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    ValidationPopup: typeof import('./src/components/ValidationPopup.vue')['default']
  }
}
